config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions"}

  resources :users

  get "/admin", to: "admin/products#index"

  get :send_updates, to: 'admin/users#send_updates', as: :send_updates

  get :update_products_from_etsy, to: 'admin/products#update_products_from_etsy', as: :update_products_from_etsy

  get :privacy_policy, to: 'home#privacy_policy', as: :privacy_policy

  resources :products do
    resources :product_measurements
  end

  resources :users do
    resources :user_measurements
  end

  namespace :admin do
    resources :products
  end

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :first_name, :last_name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :measurement, foreign_key: "user_id", class_name: "UserMeasurement", dependent: :destroy
  has_many :matches

	def match_dresses(waist, bust, hips)
		Product.joins("INNER JOIN product_measurements ON product_measurements.product_id = products.id").where(category: "Dress").where(["product_measurements.waist >= ? AND product_measurements.waist <= ?", waist - 1, waist + 2]).where(["product_measurements.bust >= ? AND product_measurements.bust <= ?", bust - 1, bust + 2]).where(["(product_measurements.hips >= ? AND product_measurements.hips <= ?) OR product_measurements.hips IS NULL", hips - 1, hips + 2])
	end

	#NOTE: category on product is saved as a string Pants, but called trousers everywhere else in the code
	#match on waist for both women and men, and lower_value is hips for women and inseam for men
	def match_trousers(waist, lower_string, lower_value, gender)
		Product.joins("INNER JOIN product_measurements ON product_measurements.product_id = products.id").where("product_measurements.gender" => gender).where(category: "Pants").where(["product_measurements.waist >= ? AND product_measurements.waist <= ?", waist - 1, waist + 2]).where(["(product_measurements.#{lower_string} >= ? AND product_measurements.#{lower_string} <= ?) OR product_measurements.#{lower_string} IS NULL", lower_value - 1, lower_value + 2])
	end

	#match on bust for women, chest for men
	def match_tops(upper_string, upper_value, gender)
		Product.joins("INNER JOIN product_measurements ON product_measurements.product_id = products.id").where("product_measurements.gender" => gender).where("category = ? OR category = ? OR category = ?", "Sweater", "Shirt", "Blouse").where(["product_measurements.#{upper_string} >= ? AND product_measurements.#{upper_string} <= ?", upper_value - 1.0, upper_value + 2.0])
	end

	def match_skirts(waist, hips)
		Product.joins("INNER JOIN product_measurements ON product_measurements.product_id = products.id").where(category: "Skirt").where(["product_measurements.waist >= ? AND product_measurements.waist <= ?", waist - 1, waist + 2]).where(["(product_measurements.hips >= ? AND product_measurements.hips <= ?) OR product_measurements.hips IS NULL", hips - 1, hips + 2])
	end

	# maybe match on waist?
	def match_jackets(upper_string, upper_value, gender)
		Product.joins("INNER JOIN product_measurements ON product_measurements.product_id = products.id").where("product_measurements.gender" => gender).where(category: "Jacket").where(["product_measurements.#{upper_string} >= ? AND product_measurements.#{upper_string} <= ?", upper_value - 1, upper_value + 2])
	end

	# again - maybe match on waist?
	def match_suits(upper_string, upper_value, gender)
		Product.joins("INNER JOIN product_measurements ON product_measurements.product_id = products.id").where("product_measurements.gender" => gender).where(category: "Suits").where(["product_measurements.#{upper_string} >= ? AND product_measurements.#{upper_string} <= ?", upper_value -1, upper_value + 2])
	end

	# returns HASH where key is the Product Category and value is an array of Product objects
	# e.g. {jackets: [product#1, product#4], suits: [product#6, product#9]}
	def match
		gender = self.measurement.gender
		matched_products = {}

		if gender == "female"
			waist = self.measurement.waist
			bust = self.measurement.bust
			hips = self.measurement.hips

			if match_dresses(waist, bust, hips)[0]
				matched_products[:dresses] = match_dresses(waist, bust, hips)
			end

			if match_skirts(waist, hips)[0]
				matched_products[:skirts] = match_skirts(waist, hips)
			end

			if match_trousers(waist, "hips", hips, gender)[0]
				matched_products[:trousers] = match_trousers(waist, "hips", hips, gender)
			end

			if match_tops("bust", bust, gender)[0]
				matched_products[:tops] = match_tops("bust", bust, gender)
			end

			if match_jackets("bust", bust, gender)[0]
				matched_products[:jackets] = match_jackets("bust", bust, gender)
			end

		else #gender will be male
			waist = self.measurement.waist
			chest = self.measurement.chest
			inseam = self.measurement.inseam

			if match_trousers(waist, "inseam", inseam, gender)[0]
				matched_products[:trousers] = match_trousers(waist, "inseam", inseam, gender)
			end

			if match_tops("chest", chest, gender)[0]
				matched_products[:tops] = match_tops("chest", chest, gender)
			end

			if match_jackets("chest", chest, gender)[0]
				matched_products[:jackets] = match_jackets("chest", chest, gender)
			end

			if match_suits("chest", chest, gender)[0]
				matched_products[:suits] = match_suits("chest", chest, gender)
			end
		end

		return matched_products
	end

	# call this method in welcome_email template
	def get_initial_matches
		initial_matches_hash = self.match
		# save each match to matches table
		if !initial_matches_hash.empty?
			initial_matches_hash.each_value do |products_array|
				products_array.each do |product|
					Match.create(product_id: product.id, user_id: self.id, emailed: true, emailed_date_time: DateTime.now)
				end
			end
		end
		return initial_matches_hash
	end

	# call this method in weekly_match_email template
	# returns a hash of matches, same format as #match method
	# note: difference between product matches, and Match model
	def get_new_matches
		# need an array of user's matches via algorithm
		all_product_matches_array = self.match_hash_flatten
		new_product_matches_array = []
		#array of old matches (in MATCH class)
		matches = self.matches

		# iterate through all the users Matches
		all_product_matches_array.each do |product|
			# if all_matches_array for this user DOES NOT include the product of this match
			# then push that product into the new_product_matches_array
			if !matches.include?(Match.find_by(product_id: product.id, user_id: self.id))
				new_product_matches_array.push(product)
			end
		end

		# now iterate over the new_product_matches_array and save each instance in the Match table
		new_product_matches_array.each do |product|
			match = Match.create(product_id: product.id, user_id: self.id, emailed: true, emailed_date_time: DateTime.now)
		end

		#reformat new_product_matches_array into hash in order to send it to email in the data format
		final = match_array_to_hash(new_product_matches_array)
		return final

	end

	def match_hash_flatten
		# self.match will include ALL product matches, new and old ones
		# also, all_matches_hash is in the format of {"skirts" => [products, etc], "jackets" => [products, etc]}
		all_matches_hash = self.match
		all_matches_array = all_matches_hash.values.flatten!
		return all_matches_array
	end

	def match_array_to_hash(array)
		conversion_hash = { "Dress" => :dresses,  "Skirt" => :skirts, "Jacket" => :jackets, "Blouse" => :tops, "Sweater" => :tops, "Shirt" => :tops, "Suits" => :suits, "Pants" => :trousers}
		hash = array.group_by { |product| product.category }
		hash = hash.map {|key, value| [conversion_hash[key], value] }.to_h
		return hash
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :destroy]
  before_filter :verify_admin

  def index
    @users = User.all
  end

  def show
    @matches = @user.match
  end

  def destroy
    @user.destroy
    redirect_to "/admin/users"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    if @user.measurement.nil?
      redirect_to new_user_user_measurement_path(current_user.id)
    else
      @matches = @user.match
    end
  end

  def edit
    # returns @user
  end

  def update
    if @user.update(user_params)
      redirect_to user_path
    else
      errs
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to "/"
    # send a flash success
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end

  def errs
    errors = @user.errors
  end
end

app/helpers/users/measurements_helper.rb
module Users::MeasurementsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container top">

<h1>Editing <%= "#{@user.first_name}" %>'s Profile</h1>

<%= form_for :user, url: user_path(@user), method: :patch do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        these edits from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="form-group">   
    <%= f.label :first_name %>
    <%= f.text_field :first_name, :class => "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, :class => "form-control" %>
  </fieldset>

  <!-- update email, password? -->

    <%= f.submit :class => "btn btn-primary"%>

<% end %>

</div>

app/views/users/privacy_policy.html.erb
<h1>OverAttired Privacy Policy</h1>

<p>This privacy policy has been compiled to better serve those who are concerned with how their 'Personally identifiable information' (PII) is being used online. PII, as used in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.</p>

<h2>What personal information do we collect from the people that visit our blog, website or app?</h2>

<p>When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address or other details to help you with your experience.</p>

<h2>When do we collect information?</h2>

<p>We collect information from you when you register on our site or enter information on our site.</p>

<h2>How do we use your information?</h2>

<p>We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:

<ul>
  <li>To personalize user's experience and to allow us to deliver the type of content and product offerings in which you are most interested.</li>
  <li>To allow us to better service you in responding to your customer service requests.</li>
  <li>To send periodic emails regarding your order or other products and services.</li>
</ul></p>

<h2>How do we protect visitor information?</h2>

<p>Our website is scanned on a regular basis for security holes and known vulnerabilities in order to make your visit to our site as safe as possible.</p>

<h2>We do not use Malware Scanning.</h2>

<p>Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems, and are required to keep the information confidential. In addition, all sensitive/credit information you supply is encrypted via Secure Socket Layer (SSL) technology.</p>

<p>We implement a variety of security measures when a user enters, submits, or accesses their information to maintain the safety of your personal information.</p>

<p>All transactions are processed through a gateway provider and are not stored or processed on our servers.</p>

<h2>Do we use 'cookies'?</h2>

<p>We do not use cookies for tracking purposes</p>

<p>You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser (like Internet Explorer) settings. Each browser is a little different, so look at your browser's Help menu to learn the correct way to modify your cookies.</p>

<p>If you disable cookies off, some features will be disabled that make your site experience more efficient and some of our services will not function properly.</p>

<h2>Third-party disclosure</h2>

<p>We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information.</p>

<h2>Third-party links</h2>

<p>We do not include or offer third-party products or services on our website.</p>

<h2>Google</h2>

<p>Google's advertising requirements can be summed up by Google's Advertising Principles. They are put in place to provide a positive experience for users. https://support.google.com/adwordspolicy/answer/1316548?hl=en</p>

<p>We have not enabled Google AdSense on our site but we may do so in the future.</p>

<h2>California Online Privacy Protection Act</h2>

<p>CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require a person or company in the United States (and conceivably the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. - See more at: http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf</p>

<p>According to CalOPPA we agree to the following: Users can visit our site anonymously. Once this privacy policy is created, we will add a link to it on our home page or as a minimum on the first significant page after entering our website. Our Privacy Policy link includes the word 'Privacy' and can be easily be found on the page specified above.</p>

<p>Users will be notified of any privacy policy changes:
  <ul>
    <li>On our Privacy Policy Page</li>
    <li>Users are able to change their personal information:</li>
      <ul>
        <li>By emailing us</li>
        <li>By calling us</li>
        <li>By logging in to their account</li>
        <li>By coming into the store personally</li>
      </ul>
    </ul></p>

<h2>How does our site handle do not track signals?</h2>

<p>We honor do not track signals and do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.</p>

<h2>Does our site allow third-party behavioral tracking?</h2>

<p>It's also important to note that we do not allow third-party behavioral tracking</p>

<h2>COPPA (Children Online Privacy Protection Act)</h2>

<p>When it comes to the collection of personal information from children under 13, the Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, the nation's consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online.</p>

<p>We do not specifically market to children under 13.</p>

<h2>Fair Information Practices</h2>

<p>The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.</p>

<p>In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur, we will notify the users via email within 7 business days</p>

<p>We also agree to the Individual Redress Principle, which requires that individuals have a right to pursue legally enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or government agencies to investigate and/or prosecute non-compliance by data processors.</p>

<h2>CAN SPAM Act</h2>

<p>The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.</p>

<p>We collect your email address in order to send information, respond to inquiries, and/or other requests or questions.</p>

<p>To be in accordance with CANSPAM we agree to the following:
  <ul>
    <li>NOT use false or misleading subjects or email addresses.</li>
    <li>Identify the message as an advertisement in some reasonable way.</li>
    <li>Include the physical address of our business or site headquarters.</li>
    <li>Monitor third-party email marketing services for compliance, if one is used.</li>
    <li>Honor opt-out/unsubscribe requests quickly.</li>
    <li>Allow users to unsubscribe by using the link at the bottom of each email.</li>
  </ul></p>

<p>If at any time you would like to unsubscribe from receiving future emails, you can email us at
overattired@gmail.com and we will promptly remove you from ALL correspondence.</p>

<h2>Contacting Us</h2>

<p>If there are any questions regarding this privacy policy you may contact us using the information below.</p>

<a href="http://overattired.herokuapp.com/">http://overattired.herokuapp.com/</a>
<br>

<div>
337 14th Ave
Oakland, CA 94612
USA
overattired@gmail.com
</div>
<br>
<p>Last Edited on 2016-02-24</p>

app/views/users/show.html.erb
<div class="container top full-container">



<div class="row info-display">
  <div class="col-md-3">
    <div class="sidebar info-display__links">

      <p><%= link_to "My Account", edit_user_path(@user) %></p>

      <% if @user.measurement %>
        <p><%= link_to "Edit My Measurements", edit_user_user_measurement_path(@user.id, @user.measurement.id) %></p>
      <% else %>
        <p><%= link_to "Add My Measurements", new_user_user_measurement_path(@user.id) %></p>
      <% end %>

      <p><%= link_to "Delete My Account", user_path(@user), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %><p>
    </div>
  </div>



  <div class="col-md-9">
  <div class="row">
      <div class="col-md-9">
        <h1><%= @user.first_name %>'s Profile</h1>
      </div>
    </div>
   <div class="row">
      <div class="col-md-12 info-display__product">
        <h3>Your Measurements</h3>
        <% if @user.measurement && @user.measurement.gender == "female"%>
          <p><strong>Bust: </strong><%= @user.measurement.bust %></p>
          <p><strong>Waist: </strong><%= @user.measurement.waist %></p>
          <p><strong>Hips: </strong><%= @user.measurement.hips %></p>
        <% elsif @user.measurement %>
          <p><strong>Chest: </strong><%= @user.measurement.chest %></p>
          <p><strong>Waist: </strong><%= @user.measurement.waist %></p>
          <p><strong>Inseam: </strong><%= @user.measurement.inseam %></p>
        <% end %>
      </div><!--col close-->
    </div><!--row close-->

    <div class="row">
      <div class="col-md-12">
        <h3>Your Matches</h3>
      </div>
    </div>

    <% @matches.each do |category, matches| %>
    <div class="row">
      <% matches.each do |match| %>
      <div class="col-md-6 info-display__product">
        <div class="info-display__details"
          <p><span class="category large"><%= category.to_s %> >></span> <span class="uppercase title emphasis"><%= match.title %></span></p>
          <p class=""><%= match.subtitle %></p>
          <p>$<%= match.price %>   |   <%= match.size %>   |   <%= match.when_made %></p>
        </div>
        <img src="<%= match.image_url %>" class="img-responsive product-image">
          <div class="row text-center">
            <a href="<%= match.url %>" class="btn btn-primary btn-sm">On Etsy >></a>
          </div>
      </div>
      <% end %>
    </div><!--row close-->
    <% end %>




  </div>
</div>
</div>
</div>