config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions"}

  resources :users

  get "/admin", to: "admin/products#index"

  get :send_updates, to: 'admin/users#send_updates', as: :send_updates

  get :update_products_from_etsy, to: 'admin/products#update_products_from_etsy', as: :update_products_from_etsy

  get :privacy_policy, to: 'home#privacy_policy', as: :privacy_policy

  resources :products do
    resources :product_measurements
  end

  resources :users do
    resources :user_measurements
  end

  namespace :admin do
    resources :products
  end

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :url, uniqueness: true
  validates :title, :url, presence: true

  has_one :measurement, foreign_key: "product_id", class_name: "ProductMeasurement", dependent: :destroy
  has_many :matches

  accepts_nested_attributes_for :measurement

  # Possible Pseudocode for valid urls
  # validate :valid_urls

  # def valid_urls
  #   valid_url("url", self.url) && valid_url("url", self.image_url)
  # end

  # private

  # def valid_url(attribute, value)
  #   unless value =~ /\A#{URI::regexp(['http', 'https'])}\z/
  #     self.errors[attribute] << (options[:message] || "is not a valid url")
  #   end
  # end

end

app/controllers/admin/products_controller.rb
require_dependency 'etsy.rb'

class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:show, :update, :destroy]
  before_action :authenticate_user!
  before_filter :verify_admin

  def index
  	@products = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
    # if @product
    #   # do your normal thing
    # else
    #   errs
    #   # render somewhere?
    # end
  end

  def create
    @product = Product.new(product_params)
    @product.active = true;
    if @product.save
      redirect_to admin_products_path
    else
      errs
      render 'new'
    end
  end

  def show
  end

  def update
    if @product.update(product_params)
      redirect_to admin_product_path(@product.id)
    else
      errs
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path
  end

  # also remove any sold products
  # def update_products_from_etsy
  #   ScrapingWorker.perform_at(20.seconds.from_now)
  #   # store_data_from_etsy
  #   redirect_to admin_products_path
  # end

private
  def product_params
    params.require(:product).permit(:title, :subtitle, :category, :when_made, :image_url, :size, :url, measurement_attributes: [:id, :gender, :hips, :waist, :chest, :inseam, :bust])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def errs
    errors = @product.errors
  end
end

app/helpers/products/measurements_helper.rb
module Products::MeasurementsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container top full-container">
<h1>Editing <%= "#{@product.title}" %></h1>

<%= form_for :product, url: admin_product_path(@product), method: :patch, html: { class: "test_class" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <fieldset class="form-group col-md-4">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control" %>
    </fieldset>
  </div>

  <div class="row">
    <fieldset class="form-group col-md-4">
      <%= f.label :subtitle %>
      <%= f.text_field :subtitle, :class => "form-control" %>
    </fieldset>
  </div>

  <div class="row">
    <fieldset class="form-group col-md-2">
      <%= f.label :price %>
      <%= f.text_field :price, :class => "form-control" %>
    </fieldset>
  </div>

  <div class="row">
    <fieldset class="form-group col-md-4">
      <%= f.label :category %>
      <%= f.text_field :category, :class => "form-control" %>
    </fieldset>
  </div>

  <div class="row">
    <fieldset class="form-group col-md-10">
      <%= f.label :url %>
      <%= f.text_field :url, :class => "form-control" %>
    </fieldset>
  </div>

  <div class="row">
    <fieldset class="form-group col-md-10">
      <%= f.label :image_url %>
      <%= f.text_field :image_url, :class => "form-control" %>
    </fieldset>
  </div>

  <div class="row">
    <fieldset class="form-group col-md-4">
      <%= f.label :size %>
      <%= f.text_field :size, :class => "form-control" %>
    </fieldset>
  </div>

  <div class="row">
    <fieldset class="form-group col-md-4">
      <%= f.label :when_made %>
      <%= f.text_field :when_made, :class => "form-control" %>
    </fieldset>
  </div>

  <div class="row">
    <fieldset class="form-group col-md-8">
      <%= f.label :description %>
      <%= f.text_area :description, :class => "form-control", :rows => "6" %>
    </fieldset>
  </div>

  <% if @product.measurement %>
    <%= f.fields_for :measurement_attributes do |measurements_form| %>

    <fieldset class="form-group">
      <%= measurements_form.radio_button :gender, 'female' %> 
      <%= measurements_form.label :gender, 'Female', :value => 'female' %>
    </fieldset>
    <fieldset class="form-group">
      <%= measurements_form.radio_button :gender, 'male' %>
      <%= measurements_form.label :gender, 'Male', :value => 'male' %>
    </fieldset>

    <% hips_range = (30..60).map { |i| [i, i]} %>
    <% hips_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :hips %>
      <%= measurements_form.select :hips, hips_range, {}, {class: "measurement-input form-control"} %>
    </fieldset>

    <% waist_range = (20..50).map { |i| [i, i]} %>
    <% waist_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :waist %>
      <%= measurements_form.select :waist, waist_range, {}, {class: "measurement-input form-control"} %>
    </fieldset>

    <% bust_range = (20..60).map { |i| [i, i]} %>
    <% bust_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :bust %>
      <%= measurements_form.select :bust, bust_range, {}, {class: "measurement-input form-control"} %>
    </fieldset>

    <% chest_range = (30..60).map { |i| [i, i]} %>
    <% chest_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :chest %>
      <%= measurements_form.select :chest, chest_range, {}, {:class => "measurement-input form-control"}%>
    </fieldset>

    <% inseam_range = (25..35).map { |i| [i, i]} %>
    <% inseam_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :inseam %>
      <%= measurements_form.select :inseam, inseam_range, {}, {:class => "measurement-input form-control"} %>
    </fieldset>

    <% shoulder_range = (14..22).map { |i| [i, i]} %>
    <% shoulder_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :shoulders %>
      <%= measurements_form.select :shoulders, shoulder_range, {}, {:class => "measurement-input form-control"} %>
    </fieldset>
    <% end %>
  <% end %>

  <%= f.submit :class => "btn btn-primary"%>

<% end %>
</div>

app/views/admin/products/index.html.erb
<div class="container top full-container">


<div class="row">
	<div class="col-md-3">
	    <div class="sidebar info-display__links">
				<p><%= link_to "Add New Product", new_admin_product_path %></p>
				<p><%= link_to "See All Customers", admin_users_path %></p>
			</div><!--side bar close-->
	  	</div><!--col close-->
	<div class="col-md-9">
	<div class="row">
		<div class="col-md-9">
		<h1>Admin Index</h1>
		</div>
	</div>
		<div class="info-display center-me">
		  <h3>Active Listings:</h3>
		  	<table class="table table-hover">
		  		<thead>
			  		<tr>
			  			<th>Title</th>
			  			<th>Subtitle</th>
			  			<th>Gender</th>
			  			<th>Category</th>
			  			<th>Decade</th>
			  		</tr>
			  	</thead>
			  	<tbody>
			  		<% @products.each do |product| %>
			  		<% if product.active %>
			  		<tr>
			  			<td><%= link_to "#{product.title}", admin_product_path(product.id) %></td>
			  			<td><%= product.subtitle %></td>
			  			<td><%= product.measurement.gender %></td>
			  			<td><%= product.category %></td>
			  			<td><%= product.when_made %></td>
			  		</tr>
			  		<% end %>
				  	<% end %>
				  </tbody>
				</table>
			</div><!--col close-->
	<div class="row col-md-9">
	<div class="info-display">
		<h3>Inactive Listings:</h3>
	  	<table class="table table-hover">
	  		<thead>
		  		<tr>
		  			<th>Title</th>
		  			<th>Subtitle</th>
		  			<th>Gender</th>
		  			<th>Category</th>
		  			<th>Decade</th>
		  		</tr>
		  	</thead>
		  	<tbody>
		  		<% @products.each do |product| %>
		  		<% if !(product.active) %>
		  		<tr>
		  			<td><%= link_to "#{product.title}", admin_product_path(product.id) %></td>
		  			<td><%= product.subtitle %></td>
		  			<td><%= product.measurement.gender %></td>
		  			<td><%= product.category %></td>
		  			<td><%= product.when_made %></td>
		  		</tr>
		  		<% end %>
			  	<% end %>
			  </tbody>
			</table>
		</div>

    </div>
  </div>
  </div><!--info display -->
</div><!-- row close -->

</div><!--container close-->

app/views/admin/products/new.html.erb
<div class="container top full-container">
<h1> Create a new product </h1>

<%= form_for :product, url: admin_products_path, method: :post, html: { class: "test_class" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <fieldset class="form-group col-md-4">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control" %>
    </fieldset>
  </div>
  
  <div class="row">
    <fieldset class="form-group col-md-4">
      <%= f.label :subtitle %>
      <%= f.text_field :subtitle, :class => "form-control" %>
    </fieldset>
  </div>
  
  <div class="row">
    <fieldset class="form-group col-md-2">
      <%= f.label :price %>
      <%= f.text_field :price, :class => "form-control" %>
    </fieldset>
  </div>
  
  <div class="row">
    <fieldset class="form-group col-md-4">
      <%= f.label :category %>
      <%= f.text_field :category, :class => "form-control" %>
    </fieldset>
  </div>
  
  <div class="row">
    <fieldset class="form-group col-md-10">
      <%= f.label :url %>
      <%= f.text_field :url, :class => "form-control" %>
    </fieldset>
  </div>
  
  <div class="row">
    <fieldset class="form-group col-md-10">
      <%= f.label :image_url %>
      <%= f.text_field :image_url, :class => "form-control" %>
    </fieldset>
  </div>
  
  <div class="row">
    <fieldset class="form-group col-md-4">
      <%= f.label :size %>
      <%= f.text_field :size, :class => "form-control" %>
    </fieldset>
  </div>
  
  <div class="row">
    <fieldset class="form-group col-md-4">
      <%= f.label :when_made, "Decade" %>
      <%= f.select :when_made, [["1920s", "1920s"], ["1930s", "1930s"], ["1940s", "1940s"], ["1950s", "1950s"], ["1960s", "1960s"], ["1970s", "1970s"], ["1980s", "1980s"]], {}, :class => "form-control" %>
    </fieldset>
  </div>
  
  <div class="row">
    <fieldset class="form-group col-md-8">
      <%= f.label :description %>
      <%= f.text_area :description, :class => "form-control", :rows => "6" %>
    </fieldset>
  </div>
  
  <%= f.fields_for :measurement_attributes do |measurements_form| %>

    <fieldset class="form-group">
      <%= measurements_form.radio_button :gender, 'female' %> 
      <%= measurements_form.label :gender, 'Female', :value => 'female' %>
    </fieldset>
    <fieldset class="form-group">
      <%= measurements_form.radio_button :gender, 'male' %>
      <%= measurements_form.label :gender, 'Male', :value => 'male' %>
    </fieldset>

    <% hips_range = (30..60).map { |i| [i, i]} %>
    <% hips_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :hips %>
      <%= measurements_form.select :hips, hips_range, {}, {class: "measurement-input form-control"} %>
    </fieldset>

    <% waist_range = (20..50).map { |i| [i, i]} %>
    <% waist_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :waist %>
      <%= measurements_form.select :waist, waist_range, {}, {class: "measurement-input form-control"} %>
    </fieldset>

    <% bust_range = (20..60).map { |i| [i, i]} %>
    <% bust_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :bust %>
      <%= measurements_form.select :bust, bust_range, {}, {class: "measurement-input form-control"} %>
    </fieldset>

    <% chest_range = (30..60).map { |i| [i, i]} %>
    <% chest_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :chest %>
      <%= measurements_form.select :chest, chest_range, {}, {:class => "measurement-input form-control"}%>
    </fieldset>

    <% inseam_range = (25..35).map { |i| [i, i]} %>
    <% inseam_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :inseam %>
      <%= measurements_form.select :inseam, inseam_range, {}, {:class => "measurement-input form-control"} %>
    </fieldset>

    <% shoulder_range = (14..22).map { |i| [i, i]} %>
    <% shoulder_range.unshift([nil, ""])%>

    <fieldset class="form-group">
      <%= measurements_form.label :shoulders %>
      <%= measurements_form.select :shoulders, shoulder_range, {}, {:class => "measurement-input form-control"} %>
    </fieldset>
  <% end %>

    <p>
      <%= f.submit %>
    </p>

<% end %>
</div>

app/views/admin/products/show.html.erb
<div class="container top full-container">

	<h1><%= "Details for #{@product.title}" %></h1>

	<div class="row info-display">
	  <div class="col-md-3">
	    <div class="sidebar info-display__links">
				<p><%= link_to "Edit Product Details", edit_admin_product_path %></p>

				<% if !@product.measurement %>
				<p><%= link_to "Add Product Measurements", new_product_measurement_path(@product.id) %></p>
				<% end %>

				<p><%= link_to "Delete Product", admin_product_path, method: :delete %></p>
				<p><%= link_to "<< Back to All Products", admin_products_path %></p>
			</div>
		</div>

		<div class="col-md-9">
	    <div class="row">
	      <div class="col-md-12">
					<h2>Product Details</h2>
					<p>
					  <strong>Title:</strong>
					  <%= @product.title %>
					</p>

					<p>
					  <strong>Sub Title:</strong>
					  <%= @product.subtitle %>
					</p>

					<p>
					  <strong>Price:</strong>
					  $ <%= @product.price %>
					</p>

					<p>
					  <strong>Category:</strong>
					  <%= @product.category %>
					</p>

					<p>
					  <strong>Decade:</strong>
					  <%= @product.when_made %>
					</p>

					<p>
					  <strong>Listing Link:</strong>
					  <a href=<%= @product.url %>><%= @product.url %></a>
					</p>

					<p>
					  <strong>Image Link:</strong>
					  <a href=<%= @product.image_url %>><%= @product.image_url %></a>
					</p>
				</div><!--col-12-close-->
			</div><!-- row close-->


			<div class="row">
		    <div class="col-md-12">

					<% if @product.measurement %>

						<h2>Product Measurements</h2>
						  <p><strong>Gender: </strong><%= @product.measurement.gender %></p>

						<% if @product.measurement.gender == 'female' || @product.measurement.gender == 'Female' %>
						  <p><strong>Hips: </strong><%= @product.measurement.hips %></p>
						  <p><strong>Waist: </strong><%= @product.measurement.waist %></p>
						  <p><strong>Bust: </strong><%= @product.measurement.bust %></p>
						  <p><strong>Shoulders: </strong><%= @product.measurement.shoulders %></p>
						<% else %>
						  <p><strong>Waist: </strong><%= @product.measurement.waist %></p>
						  <p><strong>Chest: </strong><%= @product.measurement.chest %></p>
						  <p><strong>Inseam: </strong><%= @product.measurement.inseam %></p>
						   <p><strong>Shoulders: </strong><%= @product.measurement.shoulders %></p>
						<% end %>

					<% end %>

				</div><!-- col-12-close -->
			</div><!--row close-->
	  </div><!-- col-9-close-->
	</div><!--row close-->
</div><!--container close-->